[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev --no-interaction'
]

[phases.build]
cmds = [
    'mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'